### ISSUE TITLE
如何和 Sabaki 連接？

### ISSUE THREAD

**Issue by CGLemon** [GWDx/Irene#1]
看了你的範例圖片後，平台看起來像是 Windows，那在 Windows 上是如何和 Sabaki 連接的？謝謝！

**Comment by GWDx** [comment]
我是在 Linux 下和 Sabaki 连接的，Windows 下应该差不多。

1. 首先需要在程序中实现 GTP 协议，使得运行 `python gtp.py` 时可以通过命令行交互。
2. 然后在 Sabaki 中添加引擎，运行的程序和参数分别设置为 `python` 和 `gtp.py` 的绝对路径。
